config/routes.rb
Rails.application.routes.draw do
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	resources :kittens

	# Defines the root path route ("/")
	root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
	def index
		@kittens = Kitten.all

		respond_to do |format|
			format.html
			format.json { render :json => @kittens }
		end
	end

	def show
		@kitten = Kitten.find(params[:id])

		respond_to do |format|
			format.html
			format.json { render :json => @kitten }
		end
	end

	def new
		@kitten = Kitten.new
	end

	def create
		@kitten = Kitten.new(kitten_params)

		if @kitten.save
			flash[:success] = "Kitten successfully created."
			redirect_to @kitten
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])

		if @kitten.update(kitten_params)
			flash[:success] = "Kitten successfully updated."
			redirect_to @kitten
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@kitten = Kitten.find(params[:id])
		@kitten.destroy

		flash[:success] = "Kitten successfully destroyed."
		redirect_to root_path, status: :see_other
	end

	private
	def kitten_params
		params.require(:kitten).permit(:name, :age, :cuteness, :softness)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |form|%>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :age %>
        <%= form.number_field :age %>
    </div>

    <div>
        <%= form.label :cuteness %>
        <%= form.select :cuteness, (0..10)%>
    </div>

    <div>
        <%= form.label :softness %>
        <%= form.select :softness, (0..10)%>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/kittens/_kitten.html.erb
<%= link_to kitten.name, kitten %>
<ul>
    <li> Age: <%= kitten.age %> </li>
    <li> Cuteness: <%= kitten.cuteness %> </li>
    <li> Softness: <%= kitten.softness %> </li>
</ul>

app/views/kittens/edit.html.erb
<%= render "form", kitten: @kitten %>

<%= link_to "DESTROY THIS KITTEN.", kitten_path, data: {turbo_method: :delete, turbo_confirm: 'You are about to destroy a kitten.'} %>

app/views/kittens/index.html.erb
<ul>
	<% @kittens.each do |kitten| %>
		<li>
			<%= render "kitten", kitten: kitten %>
			<%= link_to "DESTROY THIS KITTEN.", kitten_path(kitten), data: {turbo_method: :delete, turbo_confirm: 'You are about to destroy a kitten.'} %>
		</li>
		<br>
	<% end %>
</ul>

app/views/kittens/new.html.erb
<%= render "form", kitten: @kitten %>

app/views/kittens/show.html.erb
<%= render "kitten", kitten: @kitten %>

<%= link_to "Edit this kitten", edit_kitten_path %>
<%= link_to "DESTROY THIS KITTEN.", kitten_path, data: {turbo_method: :delete, turbo_confirm: 'You are about to destroy a kitten.'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittensApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= link_to "Homepage", root_path %>
      <%= link_to "Add kitten", new_kitten_path %>
      <% flash.each do |type, msg| %>
        <p>
          <%= msg %>
        </p>
      <% end %>
    </header>
    <hr>
    <main>
      <%= yield %>
    </main>
  </body>
</html>